# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fly_with_us_server.models.base_model_ import Model
from fly_with_us_server import util


class CallDemandOverwrite(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, value: int=None, reason: str=None):  # noqa: E501
        """CallDemandOverwrite - a model defined in Swagger

        :param value: The value of this CallDemandOverwrite.  # noqa: E501
        :type value: int
        :param reason: The reason of this CallDemandOverwrite.  # noqa: E501
        :type reason: str
        """
        self.swagger_types = {
            'value': int,
            'reason': str
        }

        self.attribute_map = {
            'value': 'value',
            'reason': 'reason'
        }
        self._value = value
        self._reason = reason

    @classmethod
    def from_dict(cls, dikt) -> 'CallDemandOverwrite':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CallDemandOverwrite of this CallDemandOverwrite.  # noqa: E501
        :rtype: CallDemandOverwrite
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> int:
        """Gets the value of this CallDemandOverwrite.


        :return: The value of this CallDemandOverwrite.
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value: int):
        """Sets the value of this CallDemandOverwrite.


        :param value: The value of this CallDemandOverwrite.
        :type value: int
        """

        self._value = value

    @property
    def reason(self) -> str:
        """Gets the reason of this CallDemandOverwrite.


        :return: The reason of this CallDemandOverwrite.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason: str):
        """Sets the reason of this CallDemandOverwrite.


        :param reason: The reason of this CallDemandOverwrite.
        :type reason: str
        """

        self._reason = reason
